version: 0.2

# CodeBuild spec for building and packaging SAM Lambda application
# This file packages the Lambda code for deployment via CodePipeline
# DO NOT use 'sam deploy' - deployment will be handled by CloudFormation in CodePipeline

env:
  variables:
    # AWS Region
    AWS_REGION: ap-south-1
    # S3 bucket for packaged artifacts
    S3_BUCKET: webproject-build-artifact-store
    # Project name
    PROJECT_NAME: webproject
    # CloudFormation stack name
    STACK_NAME: webproject-uploads-stack

phases:
  install:
    commands:
      - echo "=== INSTALL PHASE ==="
      - echo "Installing AWS SAM CLI and dependencies..."
      - pip install --upgrade pip
      - pip install aws-sam-cli
      - echo "Verifying AWS SAM version..."
      - sam --version
      - echo "AWS CLI is included with AWS SAM CLI"
      - aws --version
  
  pre_build:
    commands:
      - echo "=== PRE-BUILD PHASE ==="
      - echo "Current working directory:"
      - pwd
      - echo "Listing directory contents:"
      - ls -la
      - echo "Checking SAM template..."
      - test -f sam-template.yaml && echo "✓ sam-template.yaml found" || echo "✗ sam-template.yaml NOT found"
      - echo "Validating SAM template..."
      - sam validate --template sam-template.yaml --region ${AWS_REGION}
      - echo "✓ SAM template validation passed"
      - echo "Installing Lambda function dependencies..."
      - test -f src/package.json && (echo "Found Node.js package.json in src/" && cd src && npm install && cd ..) || echo "No package.json found in src/"
      - test -f src-test/package.json && (echo "Found Node.js package.json in src-test/" && cd src-test && npm install && cd ..) || echo "No package.json found in src-test/"
  
  build:
    commands:
      - echo "=== BUILD PHASE ==="
      - echo "Running tests (optional)..."
      - test -f src-test/s3-logs-handler.js && (echo "Found test file..." && cd src-test && npm test && cd ..) || echo "No test files found - skipping tests"
      - echo "Building SAM application..."
      - sam build --template sam-template.yaml --use-container
      - echo "✓ SAM build completed"
      - echo "Checking build output..."
      - ls -la .aws-sam/build/ 2>&1 || echo "Build directory not found"
      - test -f .aws-sam/build/template.yaml && echo "✓ template.yaml exists" || echo "✗ template.yaml NOT found"
  
  post_build:
    commands:
      - echo "=== POST-BUILD PHASE ==="
      - echo "Current directory $(pwd) and checking SAM template..."
      - test -f .aws-sam/build/template.yaml && echo "✓ SAM template found" || (echo "✗ ERROR template not found" && exit 1)
      - echo "Template content:"
      - cat .aws-sam/build/template.yaml
      - echo "Packaging SAM application..."
      - sam package --template-file .aws-sam/build/template.yaml --s3-bucket ${S3_BUCKET} --s3-prefix "builds/$(date +%Y%m%d-%H%M%S)" --region ${AWS_REGION} --output-template-file packaged.yaml
      - echo "✓ SAM package completed"
      - test -f packaged.yaml && echo "✓ packaged.yaml created successfully" || (echo "✗ ERROR packaged.yaml NOT created" && exit 1)
      - echo "Checking packaged.yaml location..."
      - ls -la packaged.yaml
      - pwd

artifacts:
  name: PackagedTemplate
  files:
    - packaged.yaml

cache:
  paths:
    - '/root/.cache/pip/**/*'

reports:
  CodeBuildReport:
    files:
      - packaged.yaml
    discard-paths: yes